# This controls automated builds at Travis & Shippable.

# http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false

# By default travis blacklists `gh-pages` branch.  We want it tested.
# http://docs.travis-ci.com/user/build-configuration/#Specify-branches-to-build
branches:
  only:
    - gh-pages
    - /.*/

language: node_js
# Should test the Node version that runs in production.
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions
# https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
# I believe RHcloud (openshift 2) was running 0.11 but it's being sunset anyway.
node_js:
  - 6
  - 8

# http://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/
cache:
  directories:
    - node_modules

after_script:
  - printenv

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/738a0684d6f3cc8e35ea
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
