// Generated by CoffeeScript 1.7.1
(function() {
  var assert, http, port, server, st;

  st = require('st');

  http = require('http');

  assert = require('assert');

  port = process.env.PORT || 80;

  server = http.createServer(st({
    path: process.cwd(),
    index: 'index.html'
  }));

  server.on('request', function(req, res) {
    return console.log('[%s] < %s %s', new Date().toISOString(), req.method, req.url);
  });

  server.listen(port);

  server.on('listening', function() {
    return console.log('Server up, e.g. http://localhost:' + port + '/?doc=demo');
  });

}).call(this);
